Awesome books: with ES6
Danny-imo/Awesome-Book pull request #1
Opened 2023-07-18 14:27 UTC by Danny-imo

## In this milestone**

-Create a new directory and initialize it with git.
Use npm init -y command to create package.json file.
Create the entry point for your JavaScript code called index.js
Create index.css file for your styles.
Create the main index.html file. I link my index.js and index.css files 
Create a directory called modules.
Re-create my Awesome books app following these rules:

Use ES6 syntax.
Divide my code into modules.
Create a separate file for each module in the modules directory.
Import modules into the index.js file. 
Keep all funcionalities of the app without errors.
Refactor my functions to arrow functions.
Use let and const in the correct way.
Display the current date below the navigation bar.

For this requirement i use a library [Luxon](https://moment.github.io/luxon/#/install?id=es6)
Download the library into my project using npm.
Import it as a module.

2023-07-18 16:05 UTC, Gambit142 reviewed
Hi @Danny-imo 👋, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

- Kindly remove all placeholder texts from each section in your README file. The placeholder texts look like this:

> Describe between 1-3 key features of the application.
> Add a link to your deployed project.

#### Please remove such texts in each section in your READE file. 👍  

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-07-18 19:04 UTC, OyePriscilla requested changes
Hi @Danny-imo 👏, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![so-close](https://user-images.githubusercontent.com/103386183/196423863-0f522555-1b03-455e-a452-b822cdcfc398.gif)

## Highlights
Project setup correctly ✔️ 
Current date displayed ✔️ 
Used ES6 modules to write modular JavaScript ✔️ 


## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-07-18 19:04 UTC, OyePriscilla commented on modules/bookCollection.js
> +}
- [ ] I observed this issue from your application, after I deleted a book; the remaining books were not displayed on the User Interface but it persists in the `localstorage`. Kindly resolve this blocker. 👍 

<img width="940" alt="Untitled" src="https://github.com/Danny-imo/Awesome-Book/assets/103386183/e8329630-cb3e-414b-9bdc-79c1b9a6615a">

2023-07-18 19:04 UTC, OyePriscilla commented on README.md
> +- GitHub: [@Danny-imo](https://github.com/Daniel-imo)
- [ ] - [ ] Kindly fix the `GitHub` broken link in the Author section of the README file; this will make the `README` file to be more engaging and informative. 👍

2023-07-18 19:04 UTC, OyePriscilla commented on README.md
> +    <li><a href="https://reactjs.org/">Vanila Javascript</a></li>
- [ ] I was not able to access this link, I guess the `url` is wrong and more so, optionally the link address is not pointing at JavaScript. 👍

2023-07-19 14:49 UTC, DammyShittu requested changes
Hi @Danny-imo,

## Highlights
✔️ App rendered undelete books

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-07-19 14:49 UTC, DammyShittu commented on README.md
> +- GitHub: [@Danny-imo](https://github.com/Daniel-imo)
- [ ] It looks unprofessional to have broken links on our documentation. You have not fixed the broken link issue for your github name. I think it should be `Danny-imo`, not `Daniel-imo`.

2023-07-19 15:25 UTC, tresorsawasawa approved these changes
# STATUS: APPROVE :heavy_check_mark: :heavy_check_mark:  :champagne: 

Hi @Danny-imo 
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 :clap: :clap: :100: 

![nodding-yes](https://camo.githubusercontent.com/aced9b1ffa1374fee6c3bcb9689701088f26a09dc5e75eaa59a01fd38ccc26f2/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f766d74786e78766556556f64472f67697068792e676966)

## To highlight :champagne: 
- All linters are passing :heavy_check_mark: 
- Good commit history :heavy_check_mark: 
- Good PR description :heavy_check_mark: 
- Your README file is professional :heavy_check_mark: 

## Optional suggestions
_Every comment with the **[OPTIONAL]** prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

_Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please ping me [@tresorsawasawa](https://github.com/tresorsawasawa) when you comment so I can receive the notification or use slack with the same name._

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-07-19 15:32 UTC, merged